services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    ports:
      - 8085:8085
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Berlin
      - ZIGBEE2MQTT_SERIAL_PORT=tcp://192.168.188.41:6638
      - ZIGBEE2MQTT_SERIAL_ADAPTER=ember
