client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
}

# UniFi APs und Controller im Heimnetz
client home_network {
    ipaddr = 192.168.188.0/24
    secret = u2Cn1HbGiWHSGlOvKMPVEwlMwZEdyHaKkFpkFgf4zedHCpsHzTeM2UThUbtRRUHxvhgtK263fq3FUHfOqtMOZjvxSip7w0j4cS9ZwqT33H838ZbTWeB6de2u9pBDgYi7
    shortname = home
    nastype = other
}
