proxy server {
    default_fallback = no
}

# Authentik RADIUS als Backend (PAP)
home_server authentik_radius {
    type = auth
    ipaddr = 172.28.0.10
    port = 1812
    secret = u2Cn1HbGiWHSGlOvKMPVEwlMwZEdyHaKkFpkFgf4zedHCpsHzTeM2UThUbtRRUHxvhgtK263fq3FUHfOqtMOZjvxSip7w0j4cS9ZwqT33H838ZbTWeB6de2u9pBDgYi7
    proto = udp
    response_window = 20
    zombie_period = 40
    revive_interval = 120
    status_check = none
}

home_server_pool authentik_pool {
    type = fail-over
    home_server = authentik_radius
}

realm "authentik_realm" {
    auth_pool = authentik_pool
    nostrip
}
